easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Stockings
        - App\Entity\Organisation
        - App\Entity\Location
        - App\Entity\DeviceTypes
        - App\Entity\User
