easy_admin:
    formats:
        date:     'd.m.Y'
        time:     'H:i'
        datetime: 'd.m.Y H:i'
    design:
        menu:
            - { entity: 'Stockings', icon: 'location-arrow' }
            - { entity: 'Positions', icon: 'box' }
            - { entity: 'Location', icon: 'map-marker-alt' }
            - { entity: 'Organisation', icon: 'sitemap' }
            - { entity: 'DeviceTypes', icon: 'tools' }
            - { entity: 'User', icon: 'user' }
            - { label: 'Dashboard', route: 'dashboard', icon: 'dashboard' }
    entities:
#        # List the entity class name you want to manage
        Stockings:
            class: App\Entity\Stockings
            list:
                filters: [{ property: 'position' }]
                fields: ['id', 'date', 'device_id', 'removed', 'position', 'user', 'updated', 'created']
            form:
                fields: ['date', 'device_id', 'removed', 'position', 'user']

        Organisation:
            class: App\Entity\Organisation

        Location:
            class: App\Entity\Location

        DeviceTypes:
            class: App\Entity\DeviceTypes
        User:
            class: App\Entity\User

        Positions:
            class: App\Entity\Positions
