easy_admin:
    design:
        menu:
            - { entity: 'Stockings', icon: 'location-arrow' }
            - { entity: 'Positions', icon: 'box' }
            - { entity: 'Location', icon: 'map-marker-alt' }
            - { entity: 'Organisation', icon: 'sitemap' }
            - { entity: 'DeviceTypes', icon: 'tools' }
            - { entity: 'User', icon: 'user' }
            - { label: 'Dashboard', route: 'dashboard', icon: 'dashboard' }
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Stockings
        - App\Entity\Organisation
        - App\Entity\Location
        - App\Entity\DeviceTypes
        - App\Entity\User
        - App\Entity\Positions
